export const APP_NAME = 'HumanUtils';
import {
  Type,
  ArrowRightLeft,
  Calendar,
  Lock,
  Code,
  Globe,
  Calculator,
  Palette,
  Hash,
  Binary,
  Braces,
  FileText,
  CaseSensitive,
  Link,
  FileBarChart,
} from 'lucide-react-native';

export const TOOL_CATEGORIES = [
  { id: 'text', title: 'Text Tools', icon: Type },
  { id: 'converters', title: 'Formatters & Converters', icon: ArrowRightLeft },
  { id: 'date', title: 'Date & Time', icon: Calendar },
  { id: 'crypto', title: 'Security & Crypto', icon: Lock },
  { id: 'dev', title: 'Dev & Code', icon: Code },
  { id: 'network', title: 'Network & Web', icon: Globe },
  { id: 'math', title: 'Math & Numbers', icon: Calculator },
  { id: 'colors', title: 'Colors & Images', icon: Palette },
];

export const TOOLS = [
  {
    id: 'uuid-generator',
    title: 'UUID Generator & Validator',
    description: 'Generate universally unique identifiers (v1, v4, v5, v7)',
    categories: ['dev'],
    icon: Hash,
    route: 'UuidGenerator' as const,
  },
  {
    id: 'base64-encoder',
    title: 'Base64 Encoder/Decoder',
    description: 'Encode and decode text using Base64 encoding',
    categories: ['dev', 'converters'],
    icon: Binary,
    route: 'Base64Encoder' as const,
  },
  {
    id: 'json-formatter',
    title: 'JSON Formatter & Validator',
    description: 'Format, minify, and validate JSON with error detection',
    categories: ['dev', 'converters'],
    icon: Braces,
    route: 'JsonFormatter' as const,
  },
  {
    id: 'lorem-ipsum',
    title: 'Lorem Ipsum Generator',
    description: 'Generate placeholder text for design mockups',
    categories: ['text'],
    icon: FileText,
    route: 'LoremIpsum' as const,
  },
  {
    id: 'case-converter',
    title: 'Case Converter',
    description: 'Convert text between camelCase, snake_case, kebab-case, and more',
    categories: ['text', 'dev', 'converters'],
    icon: CaseSensitive,
    route: 'CaseConverter' as const,
  },
  {
    id: 'url-encoder',
    title: 'URL Encoder/Decoder',
    description: 'Encode or decode URLs and URL components',
    categories: ['network', 'dev', 'converters'],
    icon: Link,
    route: 'UrlEncoder' as const,
  },
  {
    id: 'text-counter',
    title: 'Text Counter',
    description: 'Count characters, words, lines, sentences, and paragraphs',
    categories: ['text'],
    icon: FileBarChart,
    route: 'TextCounter' as const,
  },
];
